### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by Eomm** [Eomm/keepy-cli#36]
As titled

**Comment by abskmj** [comment]
@Eomm I would like to pick this up. I have written Github actions based workflows for a few of my npm packages.

**Comment by Eomm** [comment]
Yes, go for it!

**Comment by abskmj** [comment]
I have raised a pull request #37 with related changes.

**Comment by Eomm** [comment]
Merged, thanks for the contribution!
